"""initial_schema

Revision ID: e6306dad18d4
Revises: 
Create Date: 2026-05-05 11:02:25.304667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e6306dad18d4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('product_description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('weight_grams', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('store_location', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('store_address', sa.Text(), nullable=True),
    sa.Column('omzet_totals', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('refund_totals', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('orders_count', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_number', sa.String(length=20), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=100), nullable=False),
    sa.Column('customer_phone', sa.String(length=20), nullable=False),
    sa.Column('customer_email', sa.String(length=100), nullable=False),
    sa.Column('customer_location', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('customer_address', sa.Text(), nullable=False),
    sa.Column('shipping_cost', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('shipping_courier', sa.String(length=50), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('order_status', sa.String(length=30), nullable=False),
    sa.Column('paid_status', sa.String(length=20), nullable=False),
    sa.Column('hitpay_payment_id', sa.String(length=100), nullable=True),
    sa.Column('hitpay_payment_url', sa.String(length=500), nullable=True),
    sa.Column('is_refunded', sa.Boolean(), nullable=False),
    sa.Column('refund_reason', sa.Text(), nullable=True),
    sa.Column('handled_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['handled_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_number')
    )
    op.create_index("ix_orders_order_number",   "orders", ["order_number"],  unique=True)
    op.create_index("ix_orders_customer_email", "orders", ["customer_email"])
    op.create_index("ix_orders_order_status",   "orders", ["order_status"])
    op.create_index("ix_orders_paid_status",    "orders", ["paid_status"])
    op.create_index("ix_orders_handled_by_id",  "orders", ["handled_by_id"])
    op.create_index("ix_products_is_active",    "products", ["is_active"])
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_index("ix_products_is_active",    table_name="products")
    op.drop_index("ix_orders_handled_by_id",  table_name="orders")
    op.drop_index("ix_orders_paid_status",    table_name="orders")
    op.drop_index("ix_orders_order_status",   table_name="orders")
    op.drop_index("ix_orders_customer_email", table_name="orders")
    op.drop_index("ix_orders_order_number",   table_name="orders")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_table('users')
    op.drop_table('products')
    # ### end Alembic commands ###
